/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#dee3e8",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#004a65",
        "on-primary-fixed-variant": "#004c69",
        "secondary-container": "#34ff8d",
        "surface-variant": "#30363a",
        "on-secondary-fixed-variant": "#005228",
        "on-secondary-fixed": "#00210c",
        "on-tertiary-container": "#653a00",
        "outline": "#87929b",
        "surface-bright": "#343a3e",
        "secondary-fixed-dim": "#00e479",
        "surface-container-high": "#252b2f",
        "tertiary-fixed-dim": "#ffb86e",
        "surface-container-lowest": "#090f13",
        "surface-container-highest": "#30363a",
        "primary-fixed": "#c3e8ff",
        "error-container": "#93000a",
        "on-secondary-container": "#007239",
        "on-surface-variant": "#bcc8d1",
        "primary": "#8fd6ff",
        "on-secondary": "#003919",
        "inverse-surface": "#dee3e8",
        "secondary": "#f5fff3",
        "background": "#0e1418",
        "on-tertiary": "#492900",
        "outline-variant": "#3d4850",
        "primary-container": "#00bfff",
        "inverse-on-surface": "#2b3135",
        "tertiary-fixed": "#ffdcbd",
        "on-tertiary-fixed-variant": "#693c00",
        "on-primary-fixed": "#001e2c",
        "tertiary-container": "#fb9c24",
        "surface": "#0e1418",
        "on-error": "#690005",
        "surface-tint": "#7ad0ff",
        "on-surface": "#dee3e8",
        "on-primary": "#003549",
        "on-tertiary-fixed": "#2c1600",
        "primary-fixed-dim": "#7ad0ff",
        "error": "#ffb4ab",
        "inverse-primary": "#00668a",
        "tertiary": "#ffc184",
        "secondary-fixed": "#60ff99",
        "surface-container": "#1a2024",
        "surface-container-low": "#161c20",
        "surface-dim": "#0e1418",
        // Admin accents
        "admin-red": "#FF4444",
        "admin-gold": "#FFD700",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "lg": "24px",
        "gutter": "16px",
        "xl": "32px",
        "xs": "8px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "md": "16px",
        "base": "4px",
        "sm": "12px",
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      animation: {
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
